export const LIST = {
  ADD_ITEM   : 'LIST.ADD_ITEM',
  REMOVE_ITEM: 'LIST.REMOVE_ITEM'
};

export const ENDSEKER= {
    END : 'ENDSEKER.END',
    CALC_YEAR : 'ENDSEKER.YEAR',
    CALC_PERCENT : 'ENDSEKER.PERCENT'
};